# Generated by Django 4.2.7 on 2023-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='Full_Name',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
