# Generated by Django 4.2.7 on 2023-11-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_details_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='Hire_Date',
            field=models.DateField(db_index=True),
        ),
    ]
