# Generated by Django 4.2.7 on 2023-11-17 21:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_employee_details_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_punch_date', models.DateField(default=datetime.date.today)),
                ('first_punch_time', models.TimeField(unique=True)),
                ('last_punch_time', models.TimeField(unique=True)),
                ('leaves_in_the_month', models.CharField(max_length=40)),
                ('total_hour_working', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee_details')),
            ],
        ),
    ]
