# Generated by Django 4.2.7 on 2023-11-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancetransaction_total_hour_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetransaction',
            name='total_hour_working',
            field=models.DurationField(editable=False),
        ),
    ]
